### ISSUE TITLE
When renaming streets, addresess not changed at the same time

### ISSUE THREAD

**Issue by matthewdarwin** [Telenav/mapping#3]
I see a lot of changes where someone with a _telenav OSM address is renaming a street, but they are not also renaming the addresses along the street at the same time.

I am focused on Ottawa Canada and surrounding area.

These errors show up in the OSM inspector https://tools.geofabrik.de/osmi/  Addresses => Nodes With Addresses => Street Not Found

I have been adding comments to the changes, but there quite a lot of them.

**Comment by mvexel** [comment]
@matthewdarwin thanks for raising this, we will come up with a plan to address this, and my apologies.

Let me talk to the team and get back to you soonest.

**Comment by mvexel** [comment]
<img width="845" alt="screenshot 2017-10-11 11 38 45" src="https://user-images.githubusercontent.com/120452/31457031-c78d791c-ae78-11e7-86ee-070201f9cd6c.png">

Is [this](https://tools.geofabrik.de/osmi/?view=addresses&lon=-75.68944&lat=45.40943&zoom=11&overlays=no_addr_street,street_not_found,place_not_found,misformatted_housenumber) the view you are referring to, @matthewdarwin ?

**Comment by mvexel** [comment]
Also, our official mapping repository is at https://github.com/TelenavMapping/mapping-projects . I will move this issue there, close the issue here and delete the old repository.

**Comment by martijnv-telenav** [comment]
This issue was moved to TelenavMapping/mapping-projects#34
